name: CI

on: [push, pull_request]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install build deps
        run: sudo apt-get update && sudo apt-get install -y build-essential mingw-w64
      - name: Run make test
        run: make test
        shell: pwsh

  windows-validate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run PowerShell validator
        run: pwsh -NoProfile -ExecutionPolicy Bypass -File ./scripts/validate-lessons.ps1

  # sanitizer-check:
  #   Disabled by default: references internal `lessons/` paths which are not
  #   part of this repository. Re-enable only if sanitizer build scripts and
  #   lesson folders are present and maintained.
