name: CI

on: [push, pull_request]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install build deps
        run: sudo apt-get update && sudo apt-get install -y build-essential mingw-w64
      - name: Run make test
        run: make test
        shell: pwsh

  windows-validate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run PowerShell validator
        run: pwsh -NoProfile -ExecutionPolicy Bypass -File ./scripts/validate-lessons.ps1

  sanitizer-check:
    runs-on: ubuntu-latest
    needs: linux-build
    steps:
      - uses: actions/checkout@v4
      - name: Install gcc and sanitizer deps
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Build sanitizer-enabled lessons and run tests
        shell: bash
        run: |
          set -e
          sudo apt-get install -y pwsh
          pwsh -NoProfile -ExecutionPolicy Bypass -Command "& { ./lessons/lesson-10-dynamic-memory/build.sanitizer.ps1 }" 2>&1 | tee lesson-10-dynamic-memory.sanitizer.log || true
          pwsh -NoProfile -ExecutionPolicy Bypass -Command "& { ./lessons/lesson-17-concurrency/build.sanitizer.ps1 }" 2>&1 | tee lesson-17-concurrency.sanitizer.log || true
          pwsh -NoProfile -ExecutionPolicy Bypass -Command "& { ./lessons/lesson-17-concurrency/build.tsan.ps1 }" 2>&1 | tee lesson-17-concurrency.tsan.log || true
          # Run per-lesson test harness when available
          pwsh -NoProfile -ExecutionPolicy Bypass -File ./scripts/run-lesson-tests.ps1 -LessonPath ./lessons/lesson-10-dynamic-memory || true
        
      - name: Upload sanitizer logs
        uses: actions/upload-artifact@v4
        with:
          name: sanitizer-logs
          path: |
              lesson-10-dynamic-memory.sanitizer.log
              lesson-17-concurrency.sanitizer.log
              lesson-17-concurrency.tsan.log
