name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate expected.txt files
        shell: pwsh
        run: pwsh -NoProfile -ExecutionPolicy Bypass -File ./scripts/validate-expected.ps1

      - name: Run all builds
        shell: pwsh
        run: pwsh -NoProfile -ExecutionPolicy Bypass -File ./run-all-builds.ps1

      - name: Run project tests
        shell: pwsh
        run: pwsh -NoProfile -ExecutionPolicy Bypass -File ./scripts/run-project-tests.ps1

      - name: Run Windows-only integration tests (exe checks)
        if: runner.os == 'Windows'
        shell: pwsh
        run: pwsh -NoProfile -ExecutionPolicy Bypass -File .\tests\run-tests.ps1
