name: Lesson tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v4

    - name: Setup PowerShell
      uses: actions/setup-powershell@v2

    - name: Validate expected.txt files
      run: pwsh -NoProfile -ExecutionPolicy Bypass -File ./scripts/validate-expected.ps1

    - name: Run project tests
      run: pwsh -NoProfile -ExecutionPolicy Bypass -File ./scripts/run-project-tests.ps1
